### ISSUE TITLE
Issue With Test Code on line 37.

### ISSUE THREAD

**Issue by theschubinator** [learn-co-curriculum/js-principles-scope-lab#1]
The instructions for this lab calls for us to create a function called changeLeastFavoriteCustomer(). However, the test code calls this function reassignLeastFavorite(). It then calls it correctly on line 39. So either line 37 needs to be changed to the correction function or the instructions and line 39 need to be changed.

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-principles-scope-lab/commit/ec8b3ea87eb53bdb572381de045ec8c959800aa7. Thanks @theschubinator !
