### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by dande313** [learn-co-curriculum/js-principles-scope-lab#2]
When submitting the code for the function "attemptTwoFavoriteCustomers()" on Firefox, an Assertion Error is raised which cases every test to fail, and record it to learn as such. When run on Chrome, it works like it's supposed to.

**Comment by itzsaga** [comment]
I just ran into this issue but the student was using the LearnIDE with Chrome v56.0.2924.87 on their computer.

This is her code in her PR that I witnessed the issue with: https://github.com/learn-co-students/js-principles-scope-lab-v-000/pull/67/files

@aturkewi

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, removed this function temporarily and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
