### ISSUE TITLE
attemptTwoFavoriteCustomers errors without allowing pass

### ISSUE THREAD

**Issue by thethiingy** [learn-co-curriculum/js-principles-scope-lab#3]
Running attemptTwoFavoriteCustomers with 2 lets throws SyntaxError that causes all tests to fail (not caught). As is the solution is unpassable. I had to throw new SyntaxError to get around it.

Console error log "SyntaxError: redeclaration of let favoriteCustomer"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, removed this function temporarily and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
