### ISSUE TITLE
Issue with setBestCustomer

### ISSUE THREAD

**Issue by curlywallst** [learn-co-curriculum/js-principles-scope-lab#5]
I see that other people had issues with the last function.  Don't know if this one was broken in the fix?  The lesson wants us to declare the global variable inside the function but the test only passes with it declared outside the function.  I made a guess and it passed.  Then I looked at the solution which was the same as what I originally had.  To confirm it wasn't a typing issue I copied and pasted the solution and it doesn't pass the setBestCustomer test.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @curlywallst.

It looks like our solution branch was out of date, so we've added a working solution. The following code will work now:

```
function setBestCustomer() {
  bestCustomer = 'not bob'
}
```

Thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
